//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msit115BestOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GdsSubClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GdsSubClass()
        {
            this.Goods = new HashSet<Goods>();
        }
    
        public int GdsSubClassID { get; set; }
        public int GdsClassID { get; set; }
        public string GdsSubClass1 { get; set; }
    
        public virtual GoodsClass GoodsClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goods> Goods { get; set; }
    }
}
