//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msit115BestOne.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManPowerEntities : DbContext
    {
        public ManPowerEntities()
            : base("name=ManPowerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminArticle> AdminArticle { get; set; }
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Advertisement> Advertisement { get; set; }
        public virtual DbSet<Board> Board { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Cases> Cases { get; set; }
        public virtual DbSet<CaseStatus> CaseStatus { get; set; }
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Content> Content { get; set; }
        public virtual DbSet<Evaluation> Evaluation { get; set; }
        public virtual DbSet<GdsSubClass> GdsSubClass { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<GoodsClass> GoodsClass { get; set; }
        public virtual DbSet<ManPower> ManPower { get; set; }
        public virtual DbSet<MC_Match> MC_Match { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberStage> MemberStage { get; set; }
        public virtual DbSet<MPClass> MPClass { get; set; }
        public virtual DbSet<MPSCList> MPSCList { get; set; }
        public virtual DbSet<MPSubClass> MPSubClass { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<AdminLog> AdminLog { get; set; }
    }
}
